name: Pull Requests
on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: 15
          registry-url: https://npm.pkg.github.com
          scope: "@retro-board"
      - name: install deps
        run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_SECRET }}
      - name: post install
        run: |
          npm rebuild
          npm run prepare --if-present
      - name: tests
        run: npm test
  automerge:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GH_SECRET }}
